language: c

script: asdf plugin-test kubectx https://github.com/virtualstaticvoid/asdf-kubectx.git "kubectx version"

before_script:
  - git clone --branch v0.5.1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - jq

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install jq; fi
